CREATE TABLE IF NOT EXISTS users
              (
                  id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  email    varchar(50),
                  login    varchar(50),
                  name     varchar(50),
                  birthday date
              );

CREATE TABLE IF NOT EXISTS friendship
                  (
                      id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      requesterID int REFERENCES users (id),
                      donorID     int REFERENCES users (id),
                      status      boolean
                  );
CREATE TABLE IF NOT EXISTS films
                  (
                      id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name        varchar(200) NOT NULL,
                      description varchar(1000),
                      releaseDate date,
                      duration    int,
                      likesNumber int,
                      genre ENUM('COMEDY', 'DRAMA', 'CARTOON', 'THRILLER', 'DOCUMENTARY', 'ACTION'),
                      rate ENUM('G', 'PG', 'PG_13', 'R', 'NC_17')
                  );

CREATE TABLE IF NOT EXISTS filmLikes
                  (
                      id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      filmID int REFERENCES films (id),
                      userID int REFERENCES users (id)
                  );
