CREATE TABLE IF NOT EXISTS users
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(50),
    login    varchar(50),
    name     varchar(50),
    birthday date
);

CREATE TABLE IF NOT EXISTS friendship
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requesterID int REFERENCES users (id) ON DELETE CASCADE,
    donorID     int REFERENCES users (id) ON DELETE CASCADE,
    status      boolean
);

CREATE TABLE IF NOT EXISTS mpa
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(20)
);

CREATE TABLE IF NOT EXISTS films
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(200) NOT NULL,
    description varchar(1000),
    releaseDate date,
    duration    int,
    rate        int,
    mpaID       int REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS filmLikes
(
    id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filmID int REFERENCES films (id) ON DELETE CASCADE,
    userID int REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genre
(
    genreID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(20)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    filmID  int REFERENCES films (id) ON DELETE CASCADE,
    genreID int REFERENCES genre (genreID) ON DELETE CASCADE
);